import enum


class PipelineState(str, enum.Enum):
    SEARCH_PENDING = "SEARCH_PENDING"
    SEARCHING = "SEARCHING"
    DISCOVERED = "DISCOVERED"
    FILTER_PENDING = "FILTER_PENDING"
    FILTERED = "FILTERED"
    AUDIT_PENDING = "AUDIT_PENDING"
    AUDITING = "AUDITING"
    AUDITED = "AUDITED"
    SCORE_PENDING = "SCORE_PENDING"
    SCORED = "SCORED"
    QUALIFIED = "QUALIFIED"
    DISQUALIFIED = "DISQUALIFIED"
    RESEARCH_PENDING = "RESEARCH_PENDING"
    RESEARCHED = "RESEARCHED"
    DEMO_PENDING = "DEMO_PENDING"
    DEMO_BUILDING = "DEMO_BUILDING"
    DEMO_REVIEW = "DEMO_REVIEW"
    DEMO_READY = "DEMO_READY"
    OUTREACH_DRAFT = "OUTREACH_DRAFT"
    AWAITING_APPROVAL = "AWAITING_APPROVAL"
    CONTACTED = "CONTACTED"
    FOLLOW_UP = "FOLLOW_UP"
    REPLIED = "REPLIED"
    MEETING = "MEETING"
    WON = "WON"
    LOST = "LOST"
    ERROR = "ERROR"


class SiteClass(str, enum.Enum):
    SEM_SITE = "SEM_SITE"
    FORA_DO_AR = "FORA_DO_AR"
    REDE_SOCIAL = "REDE_SOCIAL"
    SITE_OBSOLETO = "SITE_OBSOLETO"
    SITE_FRACO = "SITE_FRACO"
    SITE_RAZOAVEL = "SITE_RAZOAVEL"
    SITE_BOM = "SITE_BOM"


class ScoreBand(str, enum.Enum):
    DESCARTAR = "DESCARTAR"
    BAIXO_POTENCIAL = "BAIXO_POTENCIAL"
    REVISAR = "REVISAR"
    ALTO_POTENCIAL = "ALTO_POTENCIAL"
    PRIORIDADE = "PRIORIDADE"


class CommercialStage(str, enum.Enum):
    NOVO = "NOVO"
    QUALIFICADO = "QUALIFICADO"
    DEMO_PRONTA = "DEMO_PRONTA"
    CONTATO_PENDENTE = "CONTATO_PENDENTE"
    CONTATADO = "CONTATADO"
    FOLLOW_UP = "FOLLOW_UP"
    RESPONDEU = "RESPONDEU"
    REUNIAO = "REUNIAO"
    GANHO = "GANHO"
    PERDIDO = "PERDIDO"


class AgentAccess(str, enum.Enum):
    OBSERVADOR = "OBSERVADOR"
    ADVICE = "ADVICE"
    OPERADOR = "OPERADOR"
    AUTONOMO = "AUTONOMO"


class ContactChannel(str, enum.Enum):
    WHATSAPP = "WHATSAPP"
    INSTAGRAM = "INSTAGRAM"
    EMAIL = "EMAIL"


class CampaignStatus(str, enum.Enum):
    DRAFT = "DRAFT"
    RUNNING = "RUNNING"
    PAUSED = "PAUSED"
    DONE = "DONE"


class JobStatus(str, enum.Enum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    DONE = "DONE"
    ERROR = "ERROR"


class TaskStatus(str, enum.Enum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    DONE = "DONE"
    FAILED = "FAILED"


class ApprovalType(str, enum.Enum):
    APPROVE_DEMO = "APPROVE_DEMO"
    API_OVER_BUDGET = "API_OVER_BUDGET"
    DELETE_DATA = "DELETE_DATA"
    OTHER = "OTHER"


class ApprovalStatus(str, enum.Enum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
